plugins {
    id 'com.android.application'
}

android {
    namespace 'com.zheng926482.xposedcarwithtrigger'   // 关键：与 AndroidManifest 的 package 保持一致
    compileSdk 34   // 或 33，根据你的 SDK 安装情况

    defaultConfig {
        applicationId "com.zheng926482.xposedcarwithtrigger"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
    compileOnly 'de.robv.android.xposed:api:82:sources'
}
